# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://blog.cuile.com/"  # Include trailing slash
# title = "瘦了就帅了"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
disqusShortname = ""

DefaultContentLanguage = "zh-cn"
# [languages]
# config/_default/languages.toml
disableLanguages = ['pt', 'en']
hasCJKLanguage = true

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
