baseurl = "https://blog.cuile.com/"
title = "瘦了就帅了"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
theme = "github-style"
languageCode = "zh-cn"
pygmentsCodeFences = true
pygmentsUseClasses = true


[params]
author = "瘦了就帅了"
description = "凡战者，以正合，以奇胜。"
location = "China Beijing"
email = "i@cuile.com"
github = "Cuile"
url = "https://blog.cuile.com"

avatar = "/images/avatar.jpg"
favicon = "/images/avatar.jpg"
headerIcon = "/images/avatar.jpg"
enableSearch = true
lastmod = true

[[params.links]]
title = "个人简历"
href = "https://gitee.com/lecui"
[[params.links]]
title = "个人简历"
href = "attachments/pdfs/_崔乐.pdf"


[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false