
[en]
  title = "Thin is handsome"
  LanguageName = "English"
  weight = 3

[pt]
  title = "Claridade" # just for the sake of showing this is possible
  LanguageName = "Português"
  weight = 2

[zh-cn]
  title = "瘦了就帅了"
  LanguageName = "简体中文"
  weight = 1
