baseURL = 'https://blog.cuile.com/'
languageCode = 'zh-CN'
title = '瘦了就帅了'
theme = 'clarity'

paginate = 10

TimeZone = 'Asia/Shanghai'
enableGitInfo = true

[taxonomies]
    tag = 'tags'
[params]
    codeLineNumbers = true
    DateFormat = "2006-01-02"
    ShowLastMod = true
[frontmatter]
    lastmod = [':git', 'lastmod', ':fileModTime', ':default']